#+title: Recipes - Dough For Pizza Napoletana - Index
#+DATE: 2024-09-27T09:49:24+10:00
#+draft: false
#+author: Maurizio Napoleoni

* Pizza 60% Hydration, 4 Balls

** Ingredients

| Ingredient  | Amount (g) |
|-------------+------------|
| Flour       | 641g       |
| Water       | 385g       |
| Salt        | 12g        |
| Yeast (dry) | 1.4g       |

** Procedure

1. Mix all the ingredients until no dry flour is visible.
   Cover with some plastic wrap or a wet cloth to prevent evaporation.
   Let it rest for about 30 minutes.


2. Every 30 to 45 minutes mix the dough with a stretch and fold method.
   Do this for about 3 times in total.

3. Let the dough rest and rise until it doubles in size.

4. At this point we can shape the dough balls.


5. Now, we need to rest the dough in the fridge for at least the next 8 hours.
   To do this I use noodle takeaway containers, which I put upside down so that
   I can rest the dough on the lid of the container and use the container as a lid.
   This also allows me to stack more dough balls on top of each other.

   Place the dough on the lid that you have just oiled:


   Cover the dough with the container itself.


   Now we can rest the dough in the fridge and let it rest.
   It can stay in the fridge anywhere between 8 and 48 hours.
   I have even kept the dough in the fridge for longer it the past, up to 1 week.

8. This is the dough after 8 hours of rest in the fridge
   ready to be transformed in pizza.

9. The pizza is now ready to be stretched and filled with ingredients.


